# Generated by Django 5.2.7 on 2025-10-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('release_year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
            ],
        ),
    ]
